version: '3'
services:
  # parser:
  #   container_name: parser 
  #   build: ./docker_parser  
  #   ports:
  #     - "5001:5001"
  #   networks:
  #     - my_net

  # db:
  #   container_name: db
  #   build: ./docker_db
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - my_net

  bot:
    container_name: bot
    build: ./docker_bot
    ports:
      - "5000:5000"
    # networks:
    #   - my_net
    # depends_on:
    #   - parser  
    #   - db
      
# networks:
#   my_net:
    
