FROM python:3.10

RUN apt-get update
RUN mkdir docker_bot
RUN mkdir docker_parser
RUN mkdir docker_db
RUN pip install requests
RUN pip install beautifulsoup4
RUN pip install pyTelegramBotAPI

COPY . .
ENTRYPOINT [ "python" ]
CMD ["./main.py"]